### ISSUE TITLE
Рассмотрение нестандартных алгоритмов

### ISSUE THREAD

**Issue by Belgrak** [Elizabeth013/Algorithms-and-sorting#2]
Я пишу вам относительно рассмотрения алгоритмов в данном репозитории. Я хотел бы уточнить, будут ли рассмотрены нестандартные алгоритмы, такие как алгоритм Форда - Фалкерсона,
![image](https://user-images.githubusercontent.com/63420603/226114724-843c2970-f788-4830-b379-34680b38bfe9.png)
так как хочу представить свою разработку и получить обратную связь от экспертов.

Если да, то, пожалуйста, сообщите мне, какие документы мне необходимо представить для рассмотрения моего нестандартного алгоритма. Я уже подготовил необходимые материалы, но хочу убедиться, что я не упустил ничего важного.

Также, если возможно, я хотел бы узнать о временных рамках, чтобы я мог подготовиться к представлению своей разработки. 

Благодарю вас за ваше время и ожидаю вашего ответа.

С уважением,

Белг

**Comment by Elizabeth013** [comment]
К сожалению, данный алгоритм рассматриваться не будет...
Но очень интересно увидеть, что вы подготовили, хотелось бы чуть больше узнать об этом алгоритме. 
Буду рада вас послушать на следующей неделе.

**Comment by Belgrak** [comment]
Хорошо, тогда считаю, что issue можно закрывать.
